added recyclerviews
lizakolot12/MyAcademyProject pull request #4
Opened 2020-12-08 12:22 UTC by lizakolot12

2020-12-08 13:01 UTC, konstzv commented on app/src/androidTest/java/ua/kolot/myacademyproject/ExampleInstrumentedTest.kt
> +import org.junit.Assert.assertEquals
откуда эти мзенения - убери

2020-12-08 13:02 UTC, konstzv commented on app/src/androidTest/java/ua/kolot/myacademyproject/ExampleInstrumentedTest.kt
> +import org.junit.Assert.assertEquals
отключи автоформатирование при коммите
сними все галки
![image](https://user-images.githubusercontent.com/5062363/101487111-bf15e100-396e-11eb-9db6-fc3a09b340a1.png)

2020-12-08 13:03 UTC, konstzv commented on app/src/main/java/ua/kolot/myacademyproject/ActorsAdapter.kt
> +    private val inflater: LayoutInflater = LayoutInflater.from(context)
разделяй сущности - не надо все слитно писать - сделай пробел перед полем
слитно пиши только те сущности которые связаны как-то

2020-12-08 13:03 UTC, konstzv commented on app/src/main/java/ua/kolot/myacademyproject/ActorsAdapter.kt
> +
лишняя строка

2020-12-08 13:05 UTC, konstzv commented on app/src/main/java/ua/kolot/myacademyproject/FragmentMoviesDetails.kt
> +        val movie = MoviesDataSource.getMovieById(arguments?.getInt(MOVIE_ID) ?: 0)
добавляй строки - дели на блоки - не надо писать сплошной простыней

2020-12-09 11:32 UTC, konstzv commented on app/src/main/java/ua/kolot/myacademyproject/FragmentMoviesDetails.kt
> +        val movie = MoviesDataSource.getMovieById(arguments?.getInt(MOVIE_ID) ?: 0)
у тебя же ошибка будет при 0 притом no such element ... не будет понятно из-за чего - можешь сразу писать типа arguments?.getInt(MOVIE_ID) ?: error("Movie id is null")

2020-12-09 11:34 UTC, konstzv commented on app/src/main/java/ua/kolot/myacademyproject/FragmentMoviesDetails.kt
> +        val actorsView = view.findViewById<RecyclerView>(R.id.actors)
обознач что это recycler - тип не приянтно писать в имени, но у recycler обычно пишут

2020-12-09 11:34 UTC, konstzv commented on app/src/main/java/ua/kolot/myacademyproject/FragmentMoviesDetails.kt
> +        val linearLayoutManager = LinearLayoutManager(context)
незачем выносить в переменную, ореинтацию можно также указать в конструкторе

2020-12-09 11:36 UTC, konstzv commented on app/src/main/java/ua/kolot/myacademyproject/FragmentMoviesDetails.kt
> +        actorsView?.layoutManager = linearLayoutManager
вьюшки делай ненулабельные

2020-12-09 11:36 UTC, konstzv commented on app/src/main/java/ua/kolot/myacademyproject/FragmentMoviesDetails.kt
> +        actorsView?.adapter = context?.let { ActorsAdapter(it, movie.actors) }
requestContext используй

2020-12-09 11:37 UTC, konstzv commented on app/src/main/java/ua/kolot/myacademyproject/FragmentMoviesList.kt
>          @JvmStatic
зачем  @JvmStatic ?

2020-12-09 11:38 UTC, konstzv commented on app/src/main/java/ua/kolot/myacademyproject/FragmentMoviesList.kt
> +            context?.let { MoviesAdapter(it, MoviesDataSource.movies(), movieClickListener) }
requestContext

2020-12-09 11:39 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_details.xml
> +            android:id="@+id/actors"
обознач что это recycler

2020-12-09 12:35 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_details.xml
> +            android:id="@+id/actors"
справа поставь констрейнт и ширину. сделай по констрейнту иначе непонятно как у тебя будут много актеров отображаться - последний точно не полностью отобразиться. попробуй штук 10 закинуть актеров

2020-12-09 12:36 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_details.xml
> +            android:id="@+id/actors"
в списке фильмов вроде такой пробелмы не будет но все равно выстави все констрейнты

2020-12-09 12:36 UTC, konstzv requested changes
исправь замечания

2020-12-09 12:43 UTC, konstzv commented on app/src/main/java/ua/kolot/myacademyproject/data/Movies.kt
> +        movies.first() { it.id == id }
смотри на подсказки студии, я бы делал firstOrNull и возврашал nullable 
it желательно не использоваться а называть как-то обдумано

2020-12-09 12:44 UTC, konstzv commented on app/src/main/java/ua/kolot/myacademyproject/data/Movies.kt
> +    fun movies(): List<Movie> = movies
почему просто movies не сделать публичными? зачем лишний метод - при том со странным названием

2020-12-09 12:45 UTC, konstzv commented on app/src/main/java/ua/kolot/myacademyproject/FragmentMoviesList.kt
> +        private const val GRID_COLUMN = 2
количество колонок я б считал из ширины экрана по отношению к ширине одной карточки

2020-12-15 14:23 UTC, lizakolot12 commented on app/src/main/java/ua/kolot/myacademyproject/FragmentMoviesList.kt
> +        private const val GRID_COLUMN = 2
Пока оставила 2

2020-12-16 14:25 UTC, konstzv commented on app/src/main/java/ua/kolot/myacademyproject/FragmentMoviesDetails.kt
> +        view.findViewById<TextView>(R.id.tv_movie_title).text = movie?.title?:""
movie не нулабельное тут - зачем ?

2020-12-16 14:29 UTC, konstzv commented on app/src/main/java/ua/kolot/myacademyproject/FragmentMoviesDetails.kt
> +        view.findViewById<TextView>(R.id.tv_movie_title).text = movie?.title?:""
форматирование ?:"" -> ?: ""

2020-12-16 14:39 UTC, lizakolot12 commented on app/src/main/java/ua/kolot/myacademyproject/FragmentMoviesDetails.kt
> +        view.findViewById<TextView>(R.id.tv_movie_title).text = movie?.title?:""
movie может быть null, ведь можно передать в moviesDataSource валидный id, а он ничего не вернет

2020-12-22 23:04 UTC, merged